FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy everything at once
COPY . .

# Restore specifically the API
RUN dotnet restore "API/API.csproj"

# Build
WORKDIR "/src/API"
RUN dotnet publish "API.csproj" -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .
ENTRYPOINT ["dotnet", "API.dll"]